--- 
################################
# BASIC PKG INFO:
# This info will be used in various places about the template
################################
# Title: single quoted string
:title: "My Great App"
# Version: Triple digit decimal number; no quotes
:version: 0.0.1
# Package ID: Single string using reverse domain nomeclature
:id: "ca.sfu.its.mygreatapp.pkg"
# Organization: Single quoted string describing a unit or department
:org: "IT Services - Vancouver Campus" 
# Company: Single quoted string describing your company
:company: "Simon Fraser University"
################################
# PKG WELCOME
# Single line: This is the blurb for the Welcome.html resource file.
# Keep it short. Quotes are optional
################################
:blurb: "A super-awesome app, guaranteed to improve your productivity."
################################
# PKG README
# These two variables produce bulleted lists. Place each bulleted item on a new line that begins
# with a hyphen. Double-quotes are optional.
################################
:overview: 
- Installs My Great App and its various components.
:details:
- "My Great App's default install location is _blank_."
- "Most of the various components are installed in _blank_."
- "To find out more about My Great App, consult your local administrator or the package's creator."
################################
# PKG LICENSE
# Single line: the license key produces a short paragraph of the how the package is licensed
# and what the rules are governing the package's distribution. 
# ALL LINES must be indented. Lines containing "\n" will be folded.
# You may split the blurb over several lines for readability. NO quoted strings.
################################
:license: 
    This package may contain software licensed under both proprietary and open source licensing contracts.
    This installer and the files it contains may not be redistributed under any circumstances. 
    Please do not copy or redistribute this software without express permission of the package maintainer. 
    This package is strictly intended for internal use only.
################################
# PACKAGEMAKER OPTIONS
################################
# If specified, packagemaker will not apply recommended permissions to package contents.
:suggested_perms: "false"
# Perform an action after installing the package. Choose one: "none", "logout", "restart" or "shutdown".
# Default is "none".
:restart: "none"
# Make the package relocatable? Default is FALSE. When set to "true", installer will try and find 
# an older version of the app bundle and overwrite it. If you set this to "true", be sure you know
# what you are doing.
:relocate: "false"
# An array of filters to be applied to the build. Any files in the pkgroot matching the one of the 
# provided regular expressions will not be bundled into the package. One filter per line, each line 
# begins with a hyphen. Double-quotes are optional.
:filter:
- .DS_Store
- .*~
# By default Packagemaker, will be verbose. Setting this to false will quiet the build.
:verbose: "true"
# This key controls the what 'style' of package we are building.
# Seting this to 10.5 will build FLAT packages.
:min_target_os_version: "10.4"
################################
# DO NOT EDIT BELOW THIS LINE
################################
# These values are autmatically generated by Boilermaker
# :creator: nil
# :created: nil
# :edited_by: nil
# :lastedit: nil
